package com.web.carpool.model.SharedModels;

public enum City {
  UNKNOWN, TORONTO, MONTREAL, VANCOUVER, EDMONTON, OTTAWA, GATINEAU, QUEBEC_CITY, HAMILTON, LONDON, VICTORIA, HALIFAX,
  OSHAWA, WINDSOR
}